### ISSUE TITLE
Days 360 February to February issue

### ISSUE THREAD

**Issue by richardxu-io** [spacecraftinc/days360#3]
The period between February 28 to February 28 of the successive (non-leap) year yields 358 days instead of the expected 360.

**Comment by davidwood** [comment]
Can you send over an example of this issue? 

2024 is a leap year and calculating against the subsequent year (`days360(new Date('2024-02-28T00:00:00.000Z'), new Date('2025-02-28T00:00:00.000Z'))`) will return 360, regardless of the method used.

Calculating from the year before the leap year using the US method (`days360(new Date('2023-02-28T00:00:00.000Z'), new Date('2024-02-28T00:00:00.000Z'))`) will return 358, as is expected and can be confirmed with Excel / Google Sheets. In this instance, the EU method will still return 360.

**Comment by richardxu-io** [comment]
Looks like I was mistaken and I was reading the wrong calculation method. Sorry for the inconvenience!
